on: push
name: Solution tests
jobs:
  runNpmTarget:
    name: Run yarn tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run jest tests
      uses: anna-money/github-actions-npm@v2